#!/usr/bin/env b bash
#configures a sever to listening to on port 80 of all servers active IPV4 IPs
sudo sed -i "s/8080/80/" /etc/nginx/sies-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid
